apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
  template:
    metadata:
      labels:
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "3.88.138.186"  # Replace with the actual IP or DNS of the Redis service
            - name: REDIS_PORT
              value: "30002"