apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001  # Choose a nodePort value within the valid range (30000-32767)
  selector:
    app: demo-voting-app